config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :users, only: :show do
    collection do
      get 'search'
    end
    member do
      get :follows, :followers
    end
    resources :follows, only: [:create, :destroy]
  end
  resources :posts, except: :index
  resources :games, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts
  has_many :games
  has_many :follower, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followee, class_name: "Follow", foreign_key: "followee_id", dependent: :destroy
  has_many :follow_user, through: :follower, source: :followee
  has_many :follower_user, through: :followee, source: :follower

  # ユーザーをフォローする
  def follow(user_id)
    follower.create(followee_id: user_id)
  end

  # ユーザーのフォローを外す
  def unfollow(user_id)
    follower.find_by(followee_id: user_id).destroy
  end

  # フォローしていればtrueを返す
  def following?(user)
    follow_user.include?(user)
  end

  # フォローされていればtrueを返す
  def followed?(user)
    follower_user.include?(user)
  end

  # 検索メソッド
  def self.search(search)
    User.where('name LIKE(?)', "%#{search}%")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show, :follows, :followers, :search]
  before_action :auto_delete, only: :show

  def show
    @user = User.find(params[:id])
    @posts = Post.order("start_time ASC").where(user_id: params[:id])
    @game = Game.new
    @games = Game.all
  end

  def follows
    user = User.find(current_user.id)
    @users = user.follow_user
  end

  def followers
    user = User.find(current_user.id)
    @users = user.follower_user
  end

  def search
    if params[:keyword] != ""
      @users = User.search(params[:keyword])
    else
      @users = User.where.not(id: current_user.id)
    end
  end

  private

  def auto_delete
    posts = Post.where("end_time < ?", Date.today)
    posts.each do |post|
      post.destroy
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/followers.html.erb
<%= render "shared/header" %>
<div class="user__contents">
  <div class="user__container">
    <div>フォロワー一覧</div>
    <% @users.each do |user| %>
      <div><%= link_to user.name, user_path(user) %><%= "　　相互" if current_user.following?(user) %>　　|<%= link_to 'フォロー', user_follows_path(user.id), method: :POST %>|</div>
    <% end %>
  </div>
</div>

app/views/users/follows.html.erb
<%= render "shared/header" %>
<div class="user__contents">
  <div class="user__container">
    <div>フォロー一覧</div>
    <br>
    <% @users.each do |user| %>
      <div><%= link_to user.name, user_path(user) %><%= "　　相互" if current_user.followed?(user) %>　　|<%= link_to 'フォロー解除', user_follow_path(user.id), method: :delete %>|</div>
    <% end %>
  </div>
</div>
<div class="user__contents">
  <div class="user__container">
<div>ユーザーを検索</div>
    <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "ユーザー名を入力", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    <div>※無記入の検索で自分以外の全てのユーザーが表示されます</div>
  </div>
</div>

app/views/users/search.html.erb
<%= render "shared/header" %>
<div class="user__contents">
  <div class="user__container">
    <div>ユーザーを検索</div>
    <%= form_with(url: search_users_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "ユーザー名を入力", class: "search-input" %>
      <%= form.submit "検索", class: "search-btn" %>
    <% end %>
    <div>※無記入の検索で自分以外の全てのユーザーが表示されます</div>
    <br>
    <div class="user__line">--------------------------------------------------------------------------------</div>
    <br>
    <div>
      <% @users.each do |user| %>
      <div>
        <%= link_to user.name, user_path(user) %>　　<%= "フォロー" if current_user.following?(user) && !(current_user.followed?(user)) %><%= "フォロワー" if !(current_user.following?(user)) && current_user.followed?(user) %><%= "相互" if current_user.following?(user) && current_user.followed?(user) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/header" %>
<% if user_signed_in? && @user == current_user %>
<div class="user__show__contents">
  <div class="user__show__container">
    <div class="follows-box">
      <div class="follows-btn"><%= link_to "フォローの一覧", follows_user_path(current_user.id) %></div>
      <div class="follows-btn"><%= link_to "フォロワーの一覧", followers_user_path(current_user.id) %></div>
    </div>
  </div>
</div>
<div class="user__show__contents">
  <div class="user__show__container">
    <div>＜ゲーム名登録フォーム＞</div>
    <div>
      <%= form_with model: @game, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <%= f.text_field :title, class:"title-input", id:"title", placeholder:"ゲーム名を入力" %>
      <%= f.submit "登録" ,class:"registration-btn" %>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="user__show__contents">
  <div class="user__show__container">
    <div>
    ＜投稿済みのゲーム名＞
    </div>
    <br>
    <div>
    <% @games.each do |game| %>
      <% if game.user_id == 1 %>
        <%= game.title %>
        <br>
      <% end %>
    <% end %> 
    <br>
    <div>-----(以下の自分が投稿したゲーム名を選択して削除)-----</div>
    <br>
    <% @games.each do |game| %>
      <% if game.user_id == current_user.id %>
        <%= link_to game.title, game_path(game.id), method: :delete %>
        <br>
      <% end %>
    <% end %>
    </div>
  </div>
</div>
<% elsif user_signed_in? && @user != current_user %>
<div class="user__show__contents">
  <div class="user__show__container">
    <div>ユーザーネーム：<%= @user.name %></div>
    <br>
    <% if current_user.following?(@user) && current_user.followed?(@user)%>
      <div>相互フォローしています！</div>
      <br>
      <div><%= link_to 'フォローを外す', user_follow_path(@user.id), method: :delete, class: "btn-sm btn-danger" %></div>
    <% elsif current_user.following?(@user) %>
      <div>フォローしています</div>
      <br>
      <div><%= link_to 'フォローを外す', user_follow_path(@user.id), method: :delete, class: "btn-sm btn-danger" %></div>
    <% else %>
      <div><%= link_to 'フォローする', user_follows_path(@user.id), method: :POST, class:"btn-sm btn-success" %></div>
    <% end %>
  </div>
</div>
<% end %>
<br>
<div class="user__show__contents">
  <div class="user__show__container">
    <div>投稿一覧(過去の情報は自動削除されます)</div>
    <div class="user__show__index">
    <% @posts.each do |post| %>
    <br>
      開始：<%= post.start_time.strftime('%Y/%m/%d %H:%M:%S') %>　終了：<%= post.end_time.strftime('%Y/%m/%d %H:%M:%S') %>　チャット：<%= post.chat.name %>　公開：<%= post.publish.name %>　<%= link_to '<削除>', post_path(post.id), method: :delete if post.user_id == current_user.id %>　<%= link_to '<編集>', edit_post_path(post.id) if post.user_id == current_user.id %>
    <% end %>
    </div>
  </div>
</div>